### ISSUE TITLE
client-secret documentation is poor

### ISSUE THREAD

**Issue by nrbw** [docusign/eg-03-java-auth-code-grant#1]
I'm trying to run the sample locally and in the application.properties file there is two value I don't seem to handle right:
```
security.oauth2.client.client-id={CLIENT_ID}
security.oauth2.client.client-secret={CLIENT_SECRET}
```
For the client-secret is it the token generated with the page https://developers.docusign.com/oauth-token-generator or is it something else ? This is not clear in the readme.md file.

When I assumed the client-id is the integration-key of my demo application I had this error when trying to login (sorry in french):
> Demande d’authentification non valide : le type de réponse n’est pas pris en charge.

When I assumed the client-id is the account-id I had this error when trying to login (sorry in french again):
> L’identifiant client fourni n’est pas enregistré dans DocuSign.

**Comment by LarryKlugerDS** [comment]
Hi @nrbw,
I'm sorry you're having this problem. "Client id" is the same as "Integration Key", so you should be using your application's Integration Key from the DocuSign Administration Tool. See the `Integrations / API and Keys` screen (link from the lower left side of the navigation links).

The error message you received, ... response type not supported... implies that you did not create the Integration Key correctly. Be sure that it is set for `Authorization Code Grant`

If you have further questions like this, please ask via stackoverflow.com with tag `docusignapi`

Thank you,
Larry
