### ISSUE TITLE
401: Authentication Failed: Could not obtain access token

### ISSUE THREAD

**Issue by mcraj017** [docusign/eg-03-java-auth-code-grant#8]
I am getting this error in the Embedded Signing Ceremony example, after getting redirected to locahost:8080/login?code=....
please advise

**Comment by LarryKlugerDS** [comment]
From your very limited description of the problem it sounds like you don't have your `DS_APP_URL` set correctly in [resources/application.properties](https://github.com/docusign/eg-03-java-auth-code-grant/blob/master/src/main/resources/application.properties)

You also need to set the `Redirect URI` for the Integration Key (client_id) correctly. See the application.properties file and the installation instructions.

**Comment by mcraj017** [comment]
I have used the default config only:
DS_APP_URL=http://localhost:8080
Redirect URI: DS_APP_URL=http://localhost:8080/login
